### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by wll-best** [nan0606/implicit-aspect-identification#1]
你好，我在运行nmf.py时遇到了这样的问题，不知道怎么办，可以帮忙解决一下吗，麻烦您了，谢谢
![image](https://user-images.githubusercontent.com/62608056/86191703-4ec29280-bb7a-11ea-86ad-08a549209a67.png)

![image](https://user-images.githubusercontent.com/62608056/86191747-6b5eca80-bb7a-11ea-9449-8638b182b7ac.png)

**Comment by wll-best** [comment]
Traceback (most recent call last):
  File "F:/a_new_study/lunwen_study/IABSA/implicit-aspect-identification/src/nmf.py", line 403, in <module>
    result = main_test("../source/ABSA-15_Restaurants_Train_Final",15)
  File "F:/a_new_study/lunwen_study/IABSA/implicit-aspect-identification/src/nmf.py", line 379, in main_test
    feature, _, sentence = list.split("],")
ValueError: not enough values to unpack (expected 3, got 1)
